---
title: Climate Action Darwin
timezone: Australia/Darwin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Climate Action Darwin is a citizen action group based in Darwin Australia
  and focused on reducing the impacts of catastrophic human-made global warming.
facebook:
  publisher: https://www.facebook.com/climateactiondarwin/
logo: "/assets/img/climate-action-darwin-logo.png"
email: climateactiondarwin@gmail.com
url: https://climateactiondarwin.org.au
twitter_username: climateactiondarwin
github_username: climateactiondarwin
repository: climateactiondarwin/climateactiondarwin.github.io
markdown: kramdown
kramdown:
  parse_block_html: true
theme: jekyll-theme-minimal
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
sass:
  sass_dir: assets/css
mailchimp-list: http://eepurl.com/bimoPf
mailchimp-form: https://ecnt.us2.list-manage.com/subscribe/post
mailchimp-signup: https://ecnt.us2.list-manage.com/subscribe/post
simple-form: https://simple-form.com/climateactiondarwin@gmail.com
cad-facebook: https://www.facebook.com/climateactiondarwin
cad-homepage: https://climateactiondarwin.org.au
